name: Build Flet Linux App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y curl git unzip xz-utils zip libglu1-mesa libgtk-3-dev
      
      # Use Flutter 3.27+ which fully supports Dart 3.9
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true
      
      - name: Verify Flutter setup
        run: |
          flutter --version
          flutter config --no-analytics
          flutter precache --linux
      
      - name: Clean Flutter cache (force rebuild)
        run: |
          flutter clean
          flutter pub cache clean -f
      
      - name: Install Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet
      
      - name: Initial Flet build (will fail, but creates structure)
        continue-on-error: true
        run: |
          flet build linux --verbose
      
      - name: Apply dependency overrides
        run: |
          cd build/linux
          cat > pubspec_overrides.yaml << 'EOF'
          dependency_overrides:
            webview_flutter_android: 3.16.0
            webview_flutter_wkwebview: 3.13.0
          EOF
      
      - name: Rebuild with overrides
        run: |
          cd build/linux
          flutter clean
          flutter pub get
          flutter build linux --release
      
      - name: Copy built app back
        run: |
          mkdir -p build/linux/x64/release/bundle
          cp -r build/linux/build/linux/x64/release/bundle/* build/linux/x64/release/bundle/ || true
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flet-linux-build
          path: build/linux/
