name: Build Linux Application Package
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyinstaller

      # 4️⃣ Install GTK and packaging tools
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev fuse libfuse2 file

      # 5️⃣ Build executable with PyInstaller
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name "edutrack" main.py

      # 6️⃣ Create application directory structure
      - name: Create app structure
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          mkdir -p AppDir/usr/share/pixmaps
          
          # Copy executable
          cp dist/edutrack AppDir/usr/bin/
          chmod +x AppDir/usr/bin/edutrack

      # 7️⃣ Create desktop entry file
      - name: Create desktop file
        run: |
          cat > AppDir/usr/share/applications/edutrack.desktop << 'EOF'
          [Desktop Entry]
          Name=EduTrack
          Comment=Educational tracking application
          Exec=edutrack
          Icon=edutrack
          Terminal=false
          Type=Application
          Categories=Education;Utility;
          EOF

      # 8️⃣ Create/copy icon (placeholder - replace with your actual icon)
      - name: Create placeholder icon
        run: |
          # If you have an icon file, copy it here instead:
          # cp icon.png AppDir/usr/share/icons/hicolor/256x256/apps/edutrack.png
          # cp icon.png AppDir/usr/share/pixmaps/edutrack.png
          
          # For now, create a simple SVG placeholder
          cat > AppDir/usr/share/pixmaps/edutrack.svg << 'EOF'
          <svg width="256" height="256" xmlns="http://www.w3.org/2000/svg">
            <rect width="256" height="256" fill="#4CAF50"/>
            <text x="128" y="140" font-size="80" text-anchor="middle" fill="white" font-family="Arial">ET</text>
          </svg>
          EOF
          
          ln -s ../pixmaps/edutrack.svg AppDir/usr/share/icons/hicolor/256x256/apps/edutrack.svg

      # 9️⃣ Create AppImage
      - name: Build AppImage
        run: |
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          
          # Create AppRun file
          cat > AppDir/AppRun << 'EOF'
          #!/bin/bash
          SELF=$(readlink -f "$0")
          HERE=${SELF%/*}
          exec "${HERE}/usr/bin/edutrack" "$@"
          EOF
          chmod +x AppDir/AppRun
          
          # Copy desktop file and icon to root
          cp AppDir/usr/share/applications/edutrack.desktop AppDir/
          cp AppDir/usr/share/pixmaps/edutrack.svg AppDir/edutrack.svg
          
          # Build AppImage
          ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir edutrack-x86_64.AppImage

      # 🔟 Create DEB package
      - name: Build DEB package
        run: |
          mkdir -p debian-package/DEBIAN
          mkdir -p debian-package/usr/bin
          mkdir -p debian-package/usr/share/applications
          mkdir -p debian-package/usr/share/icons/hicolor/256x256/apps
          
          # Copy files
          cp dist/edutrack debian-package/usr/bin/
          cp AppDir/usr/share/applications/edutrack.desktop debian-package/usr/share/applications/
          cp AppDir/usr/share/pixmaps/edutrack.svg debian-package/usr/share/icons/hicolor/256x256/apps/
          
          # Create control file
          cat > debian-package/DEBIAN/control << 'EOF'
          Package: edutrack
          Version: 1.0.0
          Section: education
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Description: Educational tracking application
           EduTrack helps you manage and track educational progress.
          EOF
          
          # Build DEB
          dpkg-deb --build debian-package edutrack_1.0.0_amd64.deb

      # 1️⃣1️⃣ Upload artifacts
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: edutrack-appimage
          path: edutrack-x86_64.AppImage

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: edutrack-deb
          path: edutrack_1.0.0_amd64.deb

      - name: Upload raw executable
        uses: actions/upload-artifact@v4
        with:
          name: edutrack-executable
          path: dist/edutrack
