name: Build macOS Executable (PyInstaller)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyinstaller

      # 4️⃣ (Optional) Install GTK if you use Flet or GUI
      - name: Install GTK (for GUI apps)
        run: |
          brew install gtk+3 || true

      # 5️⃣ Build your app
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile main.py
          ls -R dist

      # 6️⃣ Upload artifact
      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: dist/
