name: Build Linux Executable (PyInstaller)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyinstaller

      # 4️⃣ (Optional) Install GTK if you use Flet or GUI libs
      - name: Install GTK (for Flet or GUI)
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev

      # 5️⃣ Build your Python app into an executable
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name "edutrack" main.py

      # 6️⃣ Upload the built binary as artifact
      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: dist/

